### ISSUE TITLE
Ublock Origin google search filter - www.google.*##.g:has(a[href*="

### ISSUE THREAD

**Issue by nicoleahmed** [ncaq/uBlacklistRule#46]
Sorry this is in English - hope its still useful.

I use ublacklist and ublock origin on Firefox with Google UK.

Great project to get UBO and UBL lists

I noticed that for me

[www.google.*##.xpd:has([href*="1r1g.cn"])](http://www.google.*) ---- doesn't work

But 

[www.google.*##.g:has(a[href*="1r1g.cn"])](http://www.google.*) ----- this does

see here for more information: https://letsblock.it/filters/search-results

**Comment by ncaq** [comment]
I would love to fix it, but right now I am personally too busy to do so.
Also, when I do research, I basically use my PC and don't do much technical research on Android.
Also, I can't see much noise in my environment with the current filter.
Because it's built on an add-on premise?
So there is also the issue of it not being a priority for me personally.

**Comment by ncaq** [comment]
たしかに鬱陶しいのでそろそろ修正します。

**Comment by Yuki2718** [comment]
@nicoleahmed I don't think this is a matter of locale or language, but of desktop or mobile. Google uses completely different styles for each platform, which makes creating common rules difficult. The best will be use separate rule sets, but as that will cost the maintainer, I came up with this: `www.google.*###main div > div[data-hveid]:not([class]) div[class] > div[class] > a[href*="irig.cn"][data-ved]:upward(3)` Does this work for you?

**Comment by ncaq** [comment]
修正したはずです。
長いこと放置して申し訳ありませんでした。
