### ISSUE TITLE
blocking org.uk

### ISSUE THREAD

**Issue by nicoleahmed** [ncaq/uBlacklistRule#67]
Hello

Thanks for maintaining this list. sorry to write in English, I don't speak Japanese - I can use google translate if needed though...

Why are org.uk domains blocked please?
Your list looks useful but blocking org.uk domains blocks many sites that I need for work - org.uk is used mostly by professional organisations in the UK.

Thanks

**Comment by ncaq** [comment]
これは私の想定が甘かったことが原因ですね。
確か動機はcom.brドメインのスパムが大量にあることが原因です。
そこでcomとかorgとかはTLD限定で使われると思っていたため、サブドメインに存在するのはおかしいと思ったので個別対処せずに一括してブロックすることにしました。
英国で正常なサイトにも使われていることは知りませんでした。
私は日本人なので、英国における影響には気が付きませんでした。
報告ありがとうございます。
ブロックしないように変更しようと思います。

---

I guess this is due to my assumptions.
As I recall, the motive is due to the large amount of spam on the com.br domain.
So, since I thought com and org were used only for TLDs, I decided to block them all together instead of dealing with them individually because I thought it was strange that they existed in subdomains.
I did not know that they are also used for normal sites in the UK.
Since I am Japanese, I was not aware of the impact in the UK.
Thanks for the report.
I will make the change to not block them.
